name: weather_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_spinkit: ^5.2.1
  intl: ^0.19.0
  font_awesome_flutter: ^10.7.0
  geolocator: ^13.0.1
  permission_handler: ^11.3.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
